trigger:
- master
pr:
  - master

jobs:
- job: BuildImage
  displayName: 'Build image'
  pool:
    vmImage: 'ubuntu-16.04'

  steps:
  - script: |
      set -e
      VERSION=$(git describe --tags)
      echo "${VERSION}"
      echo "##vso[task.setvariable variable=version]${VERSION}"
    displayName: 'Detect version'

  - task: Docker@1
    displayName: 'Build image'
    inputs:
      dockerFile: Dockerfile
      imageName: 'openttd/website:$(version)'
      addDefaultLabels: false

  # Only publish when it triggered on 'master' (and not on a Pull Request)
  - task: Docker@1
    condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
    displayName: 'Publish image'
    inputs:
      containerregistrytype: 'Container Registry'
      dockerRegistryEndpoint: 'OpenTTD Docker Hub'
      command: 'Push an image'
      imageName: 'openttd/website:$(version)'
